# Generated by Django 4.0 on 2021-12-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('jobTitle', models.CharField(max_length=50, null=True)),
                ('programming', models.CharField(max_length=200, null=True)),
                ('languageKnown', models.CharField(max_length=200, null=True)),
                ('linkedIn', models.CharField(max_length=200, null=True)),
                ('resume', models.CharField(max_length=200, null=True)),
                ('github', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
