# Generated by Django 4.0 on 2021-12-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('ideaId', models.AutoField(primary_key=True, serialize=False)),
                ('ideaDesc', models.CharField(max_length=2000, null=True)),
                ('ideaTitle', models.CharField(default='Provide a title here', max_length=200)),
                ('ideaTags', models.CharField(default='#tags', max_length=200)),
                ('upVotes', models.IntegerField(null=True)),
                ('downVotes', models.IntegerField(null=True)),
                ('collaborators', models.IntegerField(null=True)),
                ('postingTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['ideaTags'],
            },
        ),
    ]
