# Generated by Django 4.0 on 2021-12-28 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_idea_downvotes_remove_idea_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='tempUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
