# Generated by Django 4.0 on 2021-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_idea_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='collaborators',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
