# Generated by Django 4.0 on 2021-12-28 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_idea_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='votes',
        ),
        migrations.AddField(
            model_name='idea',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='tempUser2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='tempUser1', to=settings.AUTH_USER_MODEL),
        ),
    ]
