# Generated by Django 4.0 on 2021-12-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_idea_votes_idea_downvotes_idea_upvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
