# Generated by Django 4.0 on 2021-12-28 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_delete_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='suggestions',
            field=models.ManyToManyField(blank=True, related_name='given_suggestion', through='base.SuggestionClass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionclass',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.idea'),
        ),
        migrations.AddField(
            model_name='suggestionclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
