# Generated by Django 4.0 on 2021-12-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_userinfo_id_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default='Tell us something about you', max_length=300, null=True),
        ),
    ]
