# Generated by Django 4.0 on 2021-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jobTitle',
            field=models.CharField(default='please update jobtitle', max_length=50, null=True),
        ),
    ]
