# Generated by Django 4.0 on 2022-01-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['postingTime']},
        ),
    ]
