# Generated by Django 4.0 on 2022-01-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_idea_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestionclass',
            old_name='idea',
            new_name='ideaId',
        ),
        migrations.AlterField(
            model_name='suggestionclass',
            name='content',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
