# Generated by Django 4.0 on 2022-01-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_suggestionclass_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='suggestions',
        ),
    ]
