# Generated by Django 4.0 on 2022-01-03 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_remove_idea_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionclass',
            name='ideaId',
        ),
        migrations.AddField(
            model_name='idea',
            name='suggestions',
            field=models.ManyToManyField(blank=True, related_name='given_suggestion', through='base.SuggestionClass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionclass',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestionclass',
            name='idea',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='base.idea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestionclass',
            name='content',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
